[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.17"
tokio = "1.28.0"
tracing = "0.1.38"
tracing-subscriber = "0.3.17"
